# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='msg',
        ),
        migrations.AddField(
            model_name='message',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
