# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpmanager', '0002_auto_20160602_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisanuser',
            name='otp_count',
            field=models.IntegerField(default=0),
        ),
    ]
