# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpmanager', '0004_auto_20160603_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
