# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpmanager', '0005_auto_20160603_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(default='Failed', max_length=20),
        ),
    ]
